name: Deploy 

on:
  workflow_dispatch:

  
# Before running this workflow add AWS credentials as GitHub secrets - else will get error
#     AWS_ACCESS_KEY_ID
#     AWS_SECRET_ACCESS_KEY



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # plugs in AWS secret from github
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # same
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          NOTIFY_EMAIL: ${{ secrets.NOTIFY_EMAIL }}
        run: cdk deploy --require-approval never
